name: CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake nasm valgrind

      - name: Build mozjpeg
        run: make build

      - name: Build jpeg-archive
        run: make all

      - name: Run tests
        run: make test

      - name: Run integration tests
        run: cd test && ./test.sh

      - name: Run memory leak tests
        run: ./test/memory_leak_test.sh

      - name: Run memory leak tests
        run: ./test/memory_leak_test.sh

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake nasm

      - name: Build mozjpeg
        run: make build

      - name: Build jpeg-archive
        run: make all

      - name: Run tests
        run: make test

      - name: Run integration tests
        run: cd test && ./test.sh

      - name: Run memory leak tests
        run: ./test/memory_leak_test.sh

      - name: Run memory leak tests
        run: ./test/memory_leak_test.sh

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nasm
            make

      - name: Build mozjpeg
        run: make build

      - name: Build jpeg-archive
        run: make all

      - name: Run tests
        run: make test

      - name: Run integration tests
        run: cd test && ./test.sh

      - name: Run memory leak tests
        run: ./test/memory_leak_test.sh

  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and test on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y cmake nasm gmake git valgrind
          run: |
            gmake build
            gmake all
            gmake test
            cd test && ./test.sh
            ./test/memory_leak_test.sh
