name: CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake nasm

      - name: Build mozjpeg
        run: make build

      - name: Build jpeg-archive
        run: make all

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake nasm

      - name: Build mozjpeg
        run: make build

      - name: Build jpeg-archive
        run: make all

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nasm
            make

      - name: Build mozjpeg
        run: make build

      - name: Build jpeg-archive
        run: make all

  build-linux-aarch64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          brew install qemu

      - name: Build on Linux aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y cmake nasm build-essential git
          run: |
            make build
            make all

  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y cmake nasm gmake git
          run: |
            gmake build
            gmake all